spring:
  datasource:
    url: jdbc:postgresql://dpg-csrsc4jv2p9s73bh8g10-a:5432/prod_db5
    username: prod_db5_user
    password: jeOGT1kdYDAEi4HbPadNR5Xa1mVmF0n7
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql